### ISSUE TITLE
Error on install: ModuleNotFoundError: No module named 'pkgs'

### ISSUE THREAD

**Issue by mihailangelov** [fujiawei-dev/ffmpeg-generator#2] opened 2021-06-24 07:59 UTC
Hi,
I tried to install on python 3.8.5 and 3.9.2 , but it gives an error:
ModuleNotFoundError: No module named 'pkgs'

**Comment by fujiawei-dev** [comment] 2021-06-24 08:03
pip install -U project-pkgs

**Comment by mihailangelov** [comment] 2021-06-24 08:56
Thanks, but when installing with 'pip3 install -r requirements.txt' it fails, and to avoid this I need to install all dependencies by hand first and then the 'ffmpeg-generator'. 

Content of the "requirements.txt" file:
project-pkgs==1.0.0
tqdm==4.61.1
graphviz==0.16
psutil==5.8.0
numpy==1.21.0
ffmpeg-generator==1.0.2

**Comment by fujiawei-dev** [comment] 2021-06-24 09:20
Thanks for your feedback.
I had found the cause of this bug.
I'll fix it as soon as possible.

**Comment by fujiawei-dev** [comment] 2021-06-25 02:09
This issue has been fixed in the latest commit.

**Closed as completed by fujiawei-dev** 2021-06-25 02:09 UTC
